# Generated by Django 6.0.2 on 2026-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
