# Generated by Django 6.0.2 on 2026-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_person_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_link',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
